server:
  port: ${API_GATEWAY_SERVICE_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: *
            allowedMethods: *
            allowedHeaders: *
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: room_service
          uri: lb://room-service
          predicates:
            - Path=/api/v1/rooms/**
            - Path=/api/v1/members/**
        - id: discussion_service
          uri: lb://discussion-service
          predicates:
            - Path=/api/v1/discussions/**
            - Path=/api/v1/messages/**
        - id: decision_service
          uri: lb://decision-service
          predicates:
            - Path=/api/v1/issues/**
        - id: analysis_service
          uri: lb://analysis-service
          predicates:
            - Path=/api/v1/analyses/**